### ISSUE TITLE
Unable to install TierIV C1 drivers for Jetson Xavier NX

### ISSUE THREAD

**Issue by raebelchristo-adi** [tier4/tier4_automotive_hdr_camera#29]
The details of my platform can be found here:
```
Software part of jetson-stats 4.2.12 - (c) 2024, Raffaello Bonghi
Model: Analog Devices AD-GMSL522-SL - GMSL GUI - Jetpack 5.1.3 [L4T 35.5.0]
NV Power Mode[5]: MODE_10W_DESKTOP
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3668-0001
 - Module: NVIDIA Jetson Xavier NX
Platform:
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.104-tegra
jtop:
 - Version: 4.2.12
 - Service: Active
Libraries:
 - CUDA: Not installed
 - cuDNN: Not installed
 - TensorRT: Not installed
 - VPI: Not installed
 - Vulkan: 1.3.204
 - OpenCV: 4.2.0 - with CUDA: NO
```
I have noticed that I have a similar issue related to #15 
You can find the output of error here: [error.txt](https://github.com/user-attachments/files/18147939/error.txt)
Crash output: [Crash.txt](https://github.com/user-attachments/files/18147961/Crash.txt)

I followed the same steps for clean uninstall following the script from #15 , and I too cannot be downgrading to L4T 35.4.1, which I noticed was the supported version mentioned in the released notes. Is there a possible workaround?
